version: "3.9"  # optional since v1.27.0
services:

  portainer-agent:
    image: portainer/agent:latest
    platform: linux/x86_64
    restart: always
    container_name: portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9002:9001"
    networks:
      - portainer-network
    depends_on:
      - portainer-server

  portainer-server:
    image: portainer/portainer-ce:latest
    platform: linux/x86_64
    restart: always
    container_name: portainer-server
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-server_data:/data
    networks:
      - portainer-network

volumes:
  portainer-server_data:
    name: portainer-server_data

networks:
  portainer-network:
    name: portainer-network
    driver: bridge
