// Code generated by MockGen. DO NOT EDIT.
// Source: jukebox-app/internal/misc/properties (interfaces: Properties)

// Package properties is a generated GoMock package.
package properties

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProperties is a mock of Properties interface.
type MockProperties struct {
	ctrl     *gomock.Controller
	recorder *MockPropertiesMockRecorder
}

// MockPropertiesMockRecorder is the mock recorder for MockProperties.
type MockPropertiesMockRecorder struct {
	mock *MockProperties
}

// NewMockProperties creates a new mock instance.
func NewMockProperties(ctrl *gomock.Controller) *MockProperties {
	mock := &MockProperties{ctrl: ctrl}
	mock.recorder = &MockPropertiesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProperties) EXPECT() *MockPropertiesMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockProperties) Add(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", arg0, arg1)
}

// Add indicates an expected call of Add.
func (mr *MockPropertiesMockRecorder) Add(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockProperties)(nil).Add), arg0, arg1)
}

// AsMap mocks base method.
func (m *MockProperties) AsMap() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsMap")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// AsMap indicates an expected call of AsMap.
func (mr *MockPropertiesMockRecorder) AsMap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsMap", reflect.TypeOf((*MockProperties)(nil).AsMap))
}

// Get mocks base method.
func (m *MockProperties) Get(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockPropertiesMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProperties)(nil).Get), arg0)
}
