name: 'Validate Application'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-application:
    runs-on: ubuntu-latest
    env:
      HOST_POST: ':8080'
      DATASOURCE_DRIVER: 'mysql'
      DATASOURCE_USERNAME: ${{secrets.DATASOURCE_USERNAME}}
      DATASOURCE_PASSWORD: ${{secrets.DATASOURCE_PASSWORD}}
      DATASOURCE_URL: ${{secrets.DATASOURCE_URL}}
      LOG_LEVEL: 'WARN'
      SENTRY_DSN: ${{secrets.SENTRY_DSN}}
      SENTRY_ENVIRONMENT: ${{secrets.SENTRY_ENVIRONMENT}}
      SENTRY_RELEASE: ${{secrets.SENTRY_RELEASE}}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        go: ['1.18', '1.19']

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Set up Go'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: 'Install golangci-lint'
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: 'Verify Dependencies'
        run: go mod tidy

      - name: 'Format'
        run: make format

      - name: 'Vet'
        run: make vet

      - name: 'Lint'
        run: make lint

      - name: 'Unit Test'
        run: make test

      - name: 'Compile'
        run: make compile
